Session01/Session01/Controllers/PruebaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Session01.Controllers
{
    public class PruebaController : Controller
    {
        // GET: Prueba
        public ActionResult Index() //index es el nombre de la vista - misma ves el mismo nombre de la pagina
        {
            ViewBag.mensaje = "Hola mundo";
            return View();
        }
        public ActionResult Listado()
        {
            ViewBag.nombre = "Jean";
            ViewBag.apellido = "Perea";
            ViewBag.edad = 25;
            ViewBag.estatura = 1.8;
            return View();
        }
        public ActionResult Datos() 
        {
            ViewData["id"] = 14832;
            ViewData["nom"] = "Fimon";
            ViewData["fechNac"] = new DateTime(2005, 1, 22);
            return View();
        }
    }
}

Session01/Session01/Controllers/RegistroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Session01.Controllers
{
    public class RegistroController : Controller
    {
        // GET: Registro
        [HttpGet] //PARA POST solo borra esta linea y moidifica el html Enviar
        public ActionResult Enviar(int id = 0, string nombre = null)
        {
            ViewBag.id = id;
            ViewBag.nombre = nombre;
            return View();
        }
    }
}

Session01/Session01/Views/Registro/Enviar.cshtml
@using (Html.BeginForm("Enviar", "Registro", FormMethod.Get))
{
    <p>
        @Html.Label("ID") <br />
        @Html.TextBox("id")
    </p>
    <p>
        @Html.Label("Nombre") <br />
        @Html.TextBox("nombre") 
    </p>
    <p>
        <input type="submit" value="Enviar" />
    </p>
}
<p style="color:blueviolet">
    ID: @ViewBag.id <br />
    Nombre : @ViewBag.nombre
</p>